- type: job
  id: SCPScientist
  name: Ученый SCP
  playTimeTracker: JobSCPScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 21600
  startingGear: SCPScientistGear
  icon: "SCPScientist"
  supervisors: "Главе отдела СЦП"
  canBeAntag: false
  access:
    - Research
    - Maintenance
    - External
    - SCP

- type: startingGear
  id: SCPScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtSCPScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    id: SCPSciencePDA
    ears: ClothingHeadsetSCPScience
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
